### ISSUE TITLE
installation db error

### ISSUE THREAD

**Issue by ScchutzZ** [fysiks1/amxbans#1]
it gives error like this even though everything is correct

![image](https://github.com/fysiks1/amxbans/assets/10107035/8ecc2228-32ff-4eca-b20a-b3628e986e7d)
![image](https://github.com/fysiks1/amxbans/assets/10107035/2696af16-8849-432b-9523-bf4f58740d15)

**Comment by fysiks1** [comment]
You'll probably want to verify that the permissions were actually applied properly.  Try creating a table in this database by logging into phpMyAdmin with this user's account.  Looks like you should be able to check the user's privileges for that database via the "Privileges" tab.
